"""initial schema

Revision ID: 4ee870d8ee1e
Revises: 
Create Date: 2026-04-02 15:03:59.811004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ee870d8ee1e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('name_korean', sa.String(length=200), nullable=True),
    sa.Column('name_romanized', sa.String(length=200), nullable=True),
    sa.Column('artist_type', sa.String(length=20), nullable=False),
    sa.Column('birth_name', sa.String(length=200), nullable=True),
    sa.Column('birth_name_korean', sa.String(length=200), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.Column('is_former_member', sa.Boolean(), nullable=False),
    sa.Column('spotify_id', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('spotify_id')
    )
    op.create_table('songs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('title_korean', sa.String(length=500), nullable=True),
    sa.Column('title_romanized', sa.String(length=500), nullable=True),
    sa.Column('title_japanese', sa.String(length=500), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('has_korean_ver', sa.Boolean(), nullable=False),
    sa.Column('has_english_ver', sa.Boolean(), nullable=False),
    sa.Column('has_japanese_ver', sa.Boolean(), nullable=False),
    sa.Column('release_status', sa.String(length=20), nullable=False),
    sa.Column('is_instrumental', sa.Boolean(), nullable=False),
    sa.Column('original_artist', sa.String(length=300), nullable=True),
    sa.Column('spotify_id', sa.String(length=100), nullable=True),
    sa.Column('isrc', sa.String(length=20), nullable=True),
    sa.Column('wikipedia_url', sa.String(length=500), nullable=True),
    sa.Column('fandom_url', sa.String(length=500), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isrc'),
    sa.UniqueConstraint('spotify_id')
    )
    op.create_table('artist_members',
    sa.Column('parent_artist_id', sa.Integer(), nullable=False),
    sa.Column('child_artist_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['child_artist_id'], ['artists.id'], ),
    sa.ForeignKeyConstraint(['parent_artist_id'], ['artists.id'], ),
    sa.PrimaryKeyConstraint('parent_artist_id', 'child_artist_id')
    )
    op.create_table('releases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('title_korean', sa.String(length=500), nullable=True),
    sa.Column('title_romanized', sa.String(length=500), nullable=True),
    sa.Column('release_type', sa.String(length=30), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('release_date_precision', sa.String(length=10), nullable=True),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('market', sa.String(length=10), nullable=True),
    sa.Column('catalog_number', sa.String(length=100), nullable=True),
    sa.Column('formats', sa.String(length=200), nullable=True),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.Column('wikipedia_url', sa.String(length=500), nullable=True),
    sa.Column('fandom_url', sa.String(length=500), nullable=True),
    sa.Column('cover_image_url', sa.String(length=500), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('song_credits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.Column('credit_name_raw', sa.String(length=300), nullable=True),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('song_id', 'artist_id', 'credit_name_raw', 'role', name='uq_song_credit')
    )
    op.create_table('chart_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=10), nullable=False),
    sa.Column('release_id', sa.Integer(), nullable=True),
    sa.Column('song_id', sa.Integer(), nullable=True),
    sa.Column('chart_name', sa.String(length=200), nullable=False),
    sa.Column('chart_region', sa.String(length=10), nullable=True),
    sa.Column('peak_position', sa.Integer(), nullable=True),
    sa.Column('chart_date', sa.Date(), nullable=True),
    sa.Column('certifications', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['release_id'], ['releases.id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('release_sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('release_id', sa.Integer(), nullable=False),
    sa.Column('region', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('sale_type', sa.String(length=20), nullable=True),
    sa.Column('as_of_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['release_id'], ['releases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('release_id', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('track_number', sa.Integer(), nullable=True),
    sa.Column('disc_number', sa.Integer(), nullable=True),
    sa.Column('is_title_track', sa.Boolean(), nullable=False),
    sa.Column('is_intro', sa.Boolean(), nullable=False),
    sa.Column('is_outro', sa.Boolean(), nullable=False),
    sa.Column('is_bonus', sa.Boolean(), nullable=False),
    sa.Column('version_note', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['release_id'], ['releases.id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tracks')
    op.drop_table('release_sales')
    op.drop_table('chart_entries')
    op.drop_table('song_credits')
    op.drop_table('releases')
    op.drop_table('artist_members')
    op.drop_table('songs')
    op.drop_table('artists')
    # ### end Alembic commands ###
