"""add_collaborators_table

Revision ID: 74519399055f
Revises: f649e559a69e
Create Date: 2026-04-04 16:21:51.844908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74519399055f'
down_revision: Union[str, Sequence[str], None] = 'f649e559a69e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collaborators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('song_credits', sa.Column('collaborator_id', sa.Integer(), nullable=True))

    # --- Data migration: credit_name_raw → collaborators ---
    conn = op.get_bind()

    # Insert one row per distinct collaborator name
    conn.execute(sa.text("""
        INSERT INTO collaborators (name)
        SELECT DISTINCT credit_name_raw
        FROM song_credits
        WHERE credit_name_raw IS NOT NULL
        ORDER BY credit_name_raw
    """))

    # Back-fill collaborator_id on all affected song_credits rows
    conn.execute(sa.text("""
        UPDATE song_credits sc
        SET collaborator_id = c.id
        FROM collaborators c
        WHERE sc.credit_name_raw = c.name
          AND sc.credit_name_raw IS NOT NULL
    """))
    # --- End data migration ---

    op.drop_constraint(op.f('uq_song_credit'), 'song_credits', type_='unique')
    op.create_unique_constraint('uq_song_credit', 'song_credits', ['song_id', 'artist_id', 'collaborator_id', 'role'])
    op.create_foreign_key(None, 'song_credits', 'collaborators', ['collaborator_id'], ['id'])
    op.drop_column('song_credits', 'credit_name_raw')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('song_credits', sa.Column('credit_name_raw', sa.VARCHAR(length=300), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'song_credits', type_='foreignkey')
    op.drop_constraint('uq_song_credit', 'song_credits', type_='unique')
    op.create_unique_constraint(op.f('uq_song_credit'), 'song_credits', ['song_id', 'artist_id', 'credit_name_raw', 'role'], postgresql_nulls_not_distinct=False)
    op.drop_column('song_credits', 'collaborator_id')
    op.drop_table('collaborators')
    # ### end Alembic commands ###
