"""add_spotify_id_to_releases

Revision ID: a6d0a556c97d
Revises: ced17bba4ac8
Create Date: 2026-04-05 21:48:23.579310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6d0a556c97d'
down_revision: Union[str, Sequence[str], None] = 'ced17bba4ac8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('releases', sa.Column('spotify_id', sa.String(length=100), nullable=True))
    op.create_unique_constraint('uq_releases_spotify_id', 'releases', ['spotify_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_releases_spotify_id', 'releases', type_='unique')
    op.drop_column('releases', 'spotify_id')
    # ### end Alembic commands ###
