"""add youtube_url to songs

Revision ID: f649e559a69e
Revises: b6a411184eed
Create Date: 2026-04-02 23:25:42.576954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f649e559a69e'
down_revision: Union[str, Sequence[str], None] = 'b6a411184eed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('youtube_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('songs', 'youtube_url')
    # ### end Alembic commands ###
